shallowNLP_master:
    script:
        - mvn source:jar deploy -B
    tags:
        - mvn
    only:
        - master

shallowNLP_branches:
branches:
    script:
        - mvn test -B
    tags:
        - mvn
    only:
        - branches
    except:
        - master
